import type { Question, GameModule } from "./types";

export const questions: Question[] = [
  // ─── BASICS ───────────────────────────────────────────
  {
    type: "multiple-choice",
    id: "mc-b-01",
    module: "basics",
    question: "Which keyword retrieves data from a database table?",
    options: ["INSERT", "SELECT", "UPDATE", "DELETE"],
    correctIndex: 1,
    explanation: "SELECT reads data. INSERT adds rows, UPDATE modifies them, DELETE removes them.",
  },
  {
    type: "multiple-choice",
    id: "mc-b-02",
    module: "basics",
    question: "What does SELECT * mean?",
    options: [
      "Select the first column",
      "Select all rows",
      "Select all columns",
      "Select everything and delete it",
    ],
    correctIndex: 2,
    explanation: "The asterisk (*) is a wildcard for 'all columns.' It doesn't affect which rows come back.",
  },
  {
    type: "multiple-choice",
    id: "mc-b-03",
    module: "basics",
    question: "What does the AS keyword do?",
    options: [
      "Filters rows",
      "Renames a column in the output",
      "Joins two tables",
      "Sorts results",
    ],
    correctIndex: 1,
    explanation: "AS creates an alias — a temporary rename for a column or table in the result set. The underlying data stays the same.",
  },
  {
    type: "multiple-choice",
    id: "mc-b-04",
    module: "basics",
    question: "What does DISTINCT do?",
    options: [
      "Sorts results alphabetically",
      "Removes duplicate rows from results",
      "Counts unique values",
      "Filters out NULL values",
    ],
    correctIndex: 1,
    explanation: "DISTINCT removes duplicate rows. SELECT DISTINCT state FROM customers returns each state once.",
  },
  {
    type: "query-order",
    id: "qo-b-01",
    module: "basics",
    question: "Arrange these to form a valid query that gets patient names:",
    clauses: ["FROM patients", "first_name, last_name", "SELECT", "LIMIT 10"],
    correctOrder: [2, 1, 0, 3],
    explanation: "The correct order: SELECT first_name, last_name FROM patients LIMIT 10;",
  },
  {
    type: "fill-blank",
    id: "fb-b-01",
    module: "basics",
    question: "Complete the query to get all columns from the orders table:",
    template: "_____ * FROM orders;",
    answer: "SELECT",
    acceptableAnswers: ["SELECT", "select", "Select"],
    explanation: "SELECT * FROM orders; retrieves all columns from the orders table.",
  },
  {
    type: "fill-blank",
    id: "fb-b-02",
    module: "basics",
    question: "Complete the query to rename 'name' to 'facility_name':",
    template: "SELECT name _____ facility_name FROM facilities;",
    answer: "AS",
    acceptableAnswers: ["AS", "as", "As"],
    explanation: "AS creates a column alias. SELECT name AS facility_name renames the output column.",
  },
  {
    type: "spot-the-bug",
    id: "sb-b-01",
    module: "basics",
    question: "Find the error in this query:",
    buggyQuery: "SELECT name city FROM facilities;",
    options: [
      "Missing comma between name and city",
      "Should be SELECT ALL",
      "FROM should come first",
      "Missing semicolon",
    ],
    correctIndex: 0,
    fixedQuery: "SELECT name, city FROM facilities;",
    explanation: "Column names must be separated by commas. Without the comma, SQL thinks 'city' is an alias for 'name'.",
  },

  // ─── FILTERING ────────────────────────────────────────
  {
    type: "multiple-choice",
    id: "mc-f-01",
    module: "filtering",
    question: "Which keyword filters rows in a SQL query?",
    options: ["FROM", "SELECT", "WHERE", "GROUP BY"],
    correctIndex: 2,
    explanation: "WHERE filters rows based on a condition. Only matching rows are returned.",
  },
  {
    type: "multiple-choice",
    id: "mc-f-02",
    module: "filtering",
    question: "How do you check for NULL values in SQL?",
    options: [
      "WHERE column = NULL",
      "WHERE column IS NULL",
      "WHERE column == NULL",
      "WHERE column EQUALS NULL",
    ],
    correctIndex: 1,
    explanation: "NULL isn't a value — it's the absence of one. Use IS NULL or IS NOT NULL. The = operator doesn't work with NULL.",
  },
  {
    type: "multiple-choice",
    id: "mc-f-03",
    module: "filtering",
    question: "What does the LIKE pattern '%son' match?",
    options: [
      "Only 'son'",
      "Any text ending with 'son'",
      "Any text starting with 'son'",
      "Any text containing 'son'",
    ],
    correctIndex: 1,
    explanation: "% matches any number of characters. '%son' matches 'Johnson', 'Wilson', 'son', etc.",
  },
  {
    type: "multiple-choice",
    id: "mc-f-04",
    module: "filtering",
    question: "What's the difference between AND and OR?",
    options: [
      "AND is faster than OR",
      "AND requires both conditions true; OR requires at least one",
      "They're the same",
      "AND works on numbers; OR works on text",
    ],
    correctIndex: 1,
    explanation: "AND narrows results (both must match). OR broadens results (either can match).",
  },
  {
    type: "fill-blank",
    id: "fb-f-01",
    module: "filtering",
    question: "Complete the query to find patients in California:",
    template: "SELECT * FROM patients _____ state = 'CA';",
    answer: "WHERE",
    acceptableAnswers: ["WHERE", "where", "Where"],
    explanation: "WHERE state = 'CA' filters to only California patients.",
  },
  {
    type: "fill-blank",
    id: "fb-f-02",
    module: "filtering",
    question: "Complete the query to find claims between $100 and $500:",
    template: "SELECT * FROM claims WHERE amount _____ 100 AND 500;",
    answer: "BETWEEN",
    acceptableAnswers: ["BETWEEN", "between", "Between"],
    explanation: "BETWEEN is shorthand for >= 100 AND <= 500. It's inclusive on both ends.",
  },
  {
    type: "spot-the-bug",
    id: "sb-f-01",
    module: "filtering",
    question: "This query checks for NULL values. What's wrong?",
    buggyQuery: "SELECT * FROM claims WHERE resolved_date = NULL;",
    options: [
      "Should use IS NULL instead of = NULL",
      "Missing quotes around NULL",
      "WHERE should be WHEN",
      "Need to use != NULL",
    ],
    correctIndex: 0,
    fixedQuery: "SELECT * FROM claims WHERE resolved_date IS NULL;",
    explanation: "NULL isn't a value, so = doesn't work. Use IS NULL to check for missing data.",
  },
  {
    type: "spot-the-bug",
    id: "sb-f-02",
    module: "filtering",
    question: "This query should match facilities named 'Memorial'. What's wrong?",
    buggyQuery: "SELECT * FROM facilities WHERE name LIKE 'Memorial';",
    options: [
      "Missing % wildcards",
      "LIKE should be ILIKE",
      "Need double quotes",
      "Missing FROM clause",
    ],
    correctIndex: 0,
    fixedQuery: "SELECT * FROM facilities WHERE name LIKE '%Memorial%';",
    explanation: "Without % wildcards, LIKE 'Memorial' only matches the exact string. Use '%Memorial%' to find it anywhere in the name.",
  },
  {
    type: "query-order",
    id: "qo-f-01",
    module: "filtering",
    question: "Arrange to find denied claims over $1000:",
    clauses: ["WHERE status = 'denied'", "SELECT *", "AND amount > 1000", "FROM claims"],
    correctOrder: [1, 3, 0, 2],
    explanation: "SELECT * FROM claims WHERE status = 'denied' AND amount > 1000;",
  },

  // ─── SORTING & LIMITING ───────────────────────────────
  {
    type: "multiple-choice",
    id: "mc-s-01",
    module: "sorting-limiting",
    question: "What is the default sort direction for ORDER BY?",
    options: ["DESC (descending)", "ASC (ascending)", "Random", "By primary key"],
    correctIndex: 1,
    explanation: "ORDER BY defaults to ASC: smallest to largest, A to Z, oldest to newest.",
  },
  {
    type: "multiple-choice",
    id: "mc-s-02",
    module: "sorting-limiting",
    question: "What does LIMIT 10 OFFSET 20 return?",
    options: [
      "First 10 rows",
      "First 30 rows",
      "Rows 21-30",
      "Last 10 rows",
    ],
    correctIndex: 2,
    explanation: "OFFSET 20 skips the first 20 rows, then LIMIT 10 returns the next 10 (rows 21-30).",
  },
  {
    type: "fill-blank",
    id: "fb-s-01",
    module: "sorting-limiting",
    question: "Complete the query to get the 5 most expensive claims:",
    template: "SELECT * FROM claims ORDER BY amount _____ LIMIT 5;",
    answer: "DESC",
    acceptableAnswers: ["DESC", "desc", "Desc"],
    explanation: "DESC sorts from highest to lowest. Without it, you'd get the 5 cheapest claims.",
  },
  {
    type: "query-order",
    id: "qo-s-01",
    module: "sorting-limiting",
    question: "Arrange to get the 10 newest orders:",
    clauses: ["LIMIT 10", "FROM orders", "ORDER BY order_date DESC", "SELECT *"],
    correctOrder: [3, 1, 2, 0],
    explanation: "SELECT * FROM orders ORDER BY order_date DESC LIMIT 10;",
  },
  {
    type: "spot-the-bug",
    id: "sb-s-01",
    module: "sorting-limiting",
    question: "This query should get the 5 largest facilities. What's wrong?",
    buggyQuery: "SELECT name, bed_count FROM facilities LIMIT 5 ORDER BY bed_count DESC;",
    options: [
      "LIMIT must come after ORDER BY",
      "Should use ASC instead of DESC",
      "Missing WHERE clause",
      "bed_count should be in quotes",
    ],
    correctIndex: 0,
    fixedQuery: "SELECT name, bed_count FROM facilities ORDER BY bed_count DESC LIMIT 5;",
    explanation: "LIMIT must come after ORDER BY. Otherwise you get 5 arbitrary rows, then sort those.",
  },

  // ─── AGGREGATION ──────────────────────────────────────
  {
    type: "multiple-choice",
    id: "mc-a-01",
    module: "aggregation",
    question: "What's the difference between COUNT(*) and COUNT(column)?",
    options: [
      "No difference",
      "COUNT(*) counts all rows; COUNT(column) skips NULLs",
      "COUNT(*) is faster",
      "COUNT(column) counts distinct values",
    ],
    correctIndex: 1,
    explanation: "COUNT(*) counts every row. COUNT(column) only counts rows where that column is not NULL.",
  },
  {
    type: "multiple-choice",
    id: "mc-a-02",
    module: "aggregation",
    question: "When using GROUP BY, which columns can appear in SELECT?",
    options: [
      "Any column from the table",
      "Only the grouped column(s) and aggregate functions",
      "Only aggregate functions",
      "Only the grouped column",
    ],
    correctIndex: 1,
    explanation: "SELECT can include grouped columns and aggregate functions (COUNT, SUM, AVG, etc.). Other columns are ambiguous — the engine doesn't know which row's value to pick.",
  },
  {
    type: "multiple-choice",
    id: "mc-a-03",
    module: "aggregation",
    question: "What's the difference between WHERE and HAVING?",
    options: [
      "They're interchangeable",
      "WHERE filters before grouping; HAVING filters after grouping",
      "HAVING is faster than WHERE",
      "WHERE works with text; HAVING works with numbers",
    ],
    correctIndex: 1,
    explanation: "WHERE filters rows before GROUP BY runs. HAVING filters groups after aggregation. Use HAVING with aggregate functions like COUNT or SUM.",
  },
  {
    type: "fill-blank",
    id: "fb-a-01",
    module: "aggregation",
    question: "Complete the query to count patients per state:",
    template: "SELECT state, COUNT(*) AS total FROM patients _____ state;",
    answer: "GROUP BY",
    acceptableAnswers: ["GROUP BY", "group by", "Group By", "Group by"],
    explanation: "GROUP BY state splits patients into groups by state, then COUNT(*) counts each group.",
  },
  {
    type: "fill-blank",
    id: "fb-a-02",
    module: "aggregation",
    question: "Complete the query to only show states with 100+ patients:",
    template: "SELECT state, COUNT(*) AS total FROM patients GROUP BY state _____ COUNT(*) >= 100;",
    answer: "HAVING",
    acceptableAnswers: ["HAVING", "having", "Having"],
    explanation: "HAVING filters groups. You can't use WHERE here because COUNT(*) is an aggregate that runs after grouping.",
  },
  {
    type: "query-order",
    id: "qo-a-01",
    module: "aggregation",
    question: "Arrange to get the average claim by status, only for groups > 100:",
    clauses: ["GROUP BY status", "HAVING COUNT(*) > 100", "FROM claims", "SELECT status, AVG(amount)"],
    correctOrder: [3, 2, 0, 1],
    explanation: "SELECT status, AVG(amount) FROM claims GROUP BY status HAVING COUNT(*) > 100;",
  },
  {
    type: "spot-the-bug",
    id: "sb-a-01",
    module: "aggregation",
    question: "Find the error in this query:",
    buggyQuery: "SELECT state, COUNT(*) FROM patients WHERE COUNT(*) > 50 GROUP BY state;",
    options: [
      "Should use HAVING instead of WHERE for aggregate filters",
      "COUNT(*) needs an alias",
      "Missing ORDER BY",
      "state should be in quotes",
    ],
    correctIndex: 0,
    fixedQuery: "SELECT state, COUNT(*) FROM patients GROUP BY state HAVING COUNT(*) > 50;",
    explanation: "Aggregate functions like COUNT(*) can't go in WHERE — rows haven't been grouped yet. Use HAVING to filter after aggregation.",
  },

  // ─── JOINS ────────────────────────────────────────────
  {
    type: "multiple-choice",
    id: "mc-j-01",
    module: "joins",
    question: "What does an INNER JOIN return?",
    options: [
      "All rows from both tables",
      "Only rows with matching values in both tables",
      "All rows from the left table",
      "All rows from the right table",
    ],
    correctIndex: 1,
    explanation: "INNER JOIN returns only rows with a match in both tables. No match means the row is excluded.",
  },
  {
    type: "multiple-choice",
    id: "mc-j-02",
    module: "joins",
    question: "What does a LEFT JOIN return?",
    options: [
      "Only matching rows",
      "All rows from the right table",
      "All rows from the left table, with NULLs for non-matching right rows",
      "Random rows from both tables",
    ],
    correctIndex: 2,
    explanation: "LEFT JOIN keeps every row from the left table. When no match exists in the right table, those columns fill with NULL.",
  },
  {
    type: "multiple-choice",
    id: "mc-j-03",
    module: "joins",
    question: "What does the ON clause specify in a JOIN?",
    options: [
      "Which table to join",
      "How many rows to return",
      "Which columns to match between tables",
      "The sort order",
    ],
    correctIndex: 2,
    explanation: "ON defines the join condition: which column in one table matches which column in the other.",
  },
  {
    type: "fill-blank",
    id: "fb-j-01",
    module: "joins",
    question: "Complete the JOIN to connect orders with customers:",
    template: "SELECT * FROM orders o _____ customers c ON o.customer_id = c.id;",
    answer: "JOIN",
    acceptableAnswers: ["JOIN", "join", "Join", "INNER JOIN", "inner join"],
    explanation: "JOIN (or INNER JOIN) connects orders to customers where the customer_id matches.",
  },
  {
    type: "query-order",
    id: "qo-j-01",
    module: "joins",
    question: "Arrange to get claims with patient names:",
    clauses: [
      "JOIN patients p",
      "SELECT p.first_name, c.amount",
      "ON c.patient_id = p.id",
      "FROM claims c",
    ],
    correctOrder: [1, 3, 0, 2],
    explanation: "SELECT p.first_name, c.amount FROM claims c JOIN patients p ON c.patient_id = p.id;",
  },
  {
    type: "spot-the-bug",
    id: "sb-j-01",
    module: "joins",
    question: "Find the error in this JOIN:",
    buggyQuery: "SELECT * FROM orders JOIN customers ON customer_id = id;",
    options: [
      "Ambiguous column names — need table prefixes",
      "Missing WHERE clause",
      "Should use LEFT JOIN",
      "Missing LIMIT",
    ],
    correctIndex: 0,
    fixedQuery: "SELECT * FROM orders o JOIN customers c ON o.customer_id = c.id;",
    explanation: "Both tables have an 'id' column, so the engine can't resolve which you mean. Prefix with table aliases: o.customer_id = c.id.",
  },
  {
    type: "spot-the-bug",
    id: "sb-j-02",
    module: "joins",
    question: "This query should find patients with no claims. What's wrong?",
    buggyQuery: "SELECT p.* FROM patients p JOIN claims c ON p.id = c.patient_id WHERE c.id IS NULL;",
    options: [
      "Should use LEFT JOIN instead of JOIN",
      "WHERE should be HAVING",
      "Missing GROUP BY",
      "ON clause is backwards",
    ],
    correctIndex: 0,
    fixedQuery: "SELECT p.* FROM patients p LEFT JOIN claims c ON p.id = c.patient_id WHERE c.id IS NULL;",
    explanation: "INNER JOIN drops non-matching rows, so WHERE c.id IS NULL returns nothing. LEFT JOIN keeps all patients, then WHERE filters to those with no claims.",
  },

  // ─── ADVANCED ─────────────────────────────────────────
  {
    type: "multiple-choice",
    id: "mc-v-01",
    module: "advanced",
    question: "What does a CTE (WITH clause) create?",
    options: [
      "A permanent table",
      "A temporary named result set for one query",
      "A view that persists",
      "An index for faster queries",
    ],
    correctIndex: 1,
    explanation: "A CTE defines a temporary, named result set scoped to a single query. It disappears after execution.",
  },
  {
    type: "multiple-choice",
    id: "mc-v-02",
    module: "advanced",
    question: "What's the difference between ROW_NUMBER() and RANK()?",
    options: [
      "No difference",
      "ROW_NUMBER gives unique numbers; RANK gives same number for ties",
      "RANK is faster",
      "ROW_NUMBER only works with ORDER BY",
    ],
    correctIndex: 1,
    explanation: "ROW_NUMBER assigns unique sequential numbers (1, 2, 3). RANK assigns the same number to ties and skips the next (1, 1, 3).",
  },
  {
    type: "multiple-choice",
    id: "mc-v-03",
    module: "advanced",
    question: "What does PARTITION BY do in a window function?",
    options: [
      "Splits the table into separate physical tables",
      "Divides rows into groups for the window calculation",
      "Filters out partitions",
      "Creates a new column",
    ],
    correctIndex: 1,
    explanation: "PARTITION BY splits rows into groups for the window calculation — like GROUP BY for aggregates, but without collapsing rows.",
  },
  {
    type: "fill-blank",
    id: "fb-v-01",
    module: "advanced",
    question: "Complete the CASE expression to label claims over $5000 as 'Large':",
    template: "SELECT amount, _____ WHEN amount > 5000 THEN 'Large' ELSE 'Small' END AS label FROM claims;",
    answer: "CASE",
    acceptableAnswers: ["CASE", "case", "Case"],
    explanation: "CASE WHEN ... THEN ... ELSE ... END is SQL's conditional logic. Think of it as an inline if/else.",
  },
  {
    type: "fill-blank",
    id: "fb-v-02",
    module: "advanced",
    question: "Complete the CTE syntax:",
    template: "_____ monthly AS (SELECT month, SUM(amount) FROM claims GROUP BY month) SELECT * FROM monthly;",
    answer: "WITH",
    acceptableAnswers: ["WITH", "with", "With"],
    explanation: "WITH starts a CTE definition. The name after WITH becomes a temporary table you can query.",
  },
  {
    type: "query-order",
    id: "qo-v-01",
    module: "advanced",
    question: "Arrange to create a CTE then query it:",
    clauses: [
      "SELECT * FROM totals",
      "WITH totals AS (",
      "SELECT status, COUNT(*) AS n FROM claims GROUP BY status",
      ")",
    ],
    correctOrder: [1, 2, 3, 0],
    explanation: "WITH totals AS (SELECT status, COUNT(*) AS n FROM claims GROUP BY status) SELECT * FROM totals;",
  },
  {
    type: "spot-the-bug",
    id: "sb-v-01",
    module: "advanced",
    question: "Does this window function have a bug?",
    buggyQuery: "SELECT name, RANK() OVER (ORDER BY amount) AS rank FROM claims;",
    options: [
      "RANK() needs a column argument",
      "Missing PARTITION BY",
      "Nothing — this query is valid",
      "OVER should be WITHIN",
    ],
    correctIndex: 2,
    fixedQuery: "SELECT name, RANK() OVER (ORDER BY amount) AS rank FROM claims;",
    explanation: "This query is valid. RANK() takes no arguments, and PARTITION BY is optional. Without it, the entire result set is one partition.",
  },
];

export function getQuestionsByModule(module: GameModule): Question[] {
  return questions.filter((q) => q.module === module);
}

export function getQuestionCountByModule(): Record<GameModule, number> {
  const counts: Record<string, number> = {};
  for (const q of questions) {
    counts[q.module] = (counts[q.module] || 0) + 1;
  }
  return counts as Record<GameModule, number>;
}
